//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERECRUITMENT_BROADCASTER.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2940259")]
        public int TLSHARP_API_ID {
            get {
                return ((int)(this["TLSHARP_API_ID"]));
            }
            set {
                this["TLSHARP_API_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("323e8fbc78238ba9dae75b691579770b")]
        public string TLSHARP_API_HASH {
            get {
                return ((string)(this["TLSHARP_API_HASH"]));
            }
            set {
                this["TLSHARP_API_HASH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+6287714444433")]
        public string TLSHARP_API_SENDER {
            get {
                return ((string)(this["TLSHARP_API_SENDER"]));
            }
            set {
                this["TLSHARP_API_SENDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string TLSHARP_API_AUTHCODE {
            get {
                return ((string)(this["TLSHARP_API_AUTHCODE"]));
            }
            set {
                this["TLSHARP_API_AUTHCODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TLSHARP_SESSION_ID {
            get {
                return ((string)(this["TLSHARP_SESSION_ID"]));
            }
            set {
                this["TLSHARP_SESSION_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TLSHARP_SESSION_LASTMSGID {
            get {
                return ((string)(this["TLSHARP_SESSION_LASTMSGID"]));
            }
            set {
                this["TLSHARP_SESSION_LASTMSGID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TLSHARP_SESSION_SALT {
            get {
                return ((string)(this["TLSHARP_SESSION_SALT"]));
            }
            set {
                this["TLSHARP_SESSION_SALT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TLSHARP_SESSION_SESSEXP {
            get {
                return ((string)(this["TLSHARP_SESSION_SESSEXP"]));
            }
            set {
                this["TLSHARP_SESSION_SESSEXP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TLSHARP_SESSION_SEQ {
            get {
                return ((string)(this["TLSHARP_SESSION_SEQ"]));
            }
            set {
                this["TLSHARP_SESSION_SEQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TLSHARP_SESSION_SESSID {
            get {
                return ((string)(this["TLSHARP_SESSION_SESSID"]));
            }
            set {
                this["TLSHARP_SESSION_SESSID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TLSHARP_SESSION_HASH {
            get {
                return ((string)(this["TLSHARP_SESSION_HASH"]));
            }
            set {
                this["TLSHARP_SESSION_HASH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal APP_MSG_DEL {
            get {
                return ((decimal)(this["APP_MSG_DEL"]));
            }
            set {
                this["APP_MSG_DEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_MSG_FRMT {
            get {
                return ((string)(this["APP_MSG_FRMT"]));
            }
            set {
                this["APP_MSG_FRMT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\172.18.100.125\\hrd_common\\20. RECRUITMENT\\40. ERECRUITMENT\\ERECRUITMENT LOG")]
        public string APP_RPT_DIR {
            get {
                return ((string)(this["APP_RPT_DIR"]));
            }
            set {
                this["APP_RPT_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHIMANOIT2020")]
        public string APP_RPT_PASS {
            get {
                return ((string)(this["APP_RPT_PASS"]));
            }
            set {
                this["APP_RPT_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\172.18.100.125\\hrd_common\\20. RECRUITMENT\\40. ERECRUITMENT\\ERECRUITMENT QR")]
        public string APP_IMG_DIR {
            get {
                return ((string)(this["APP_IMG_DIR"]));
            }
            set {
                this["APP_IMG_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TES TERTULIS")]
        public string APP_MSG_TTL {
            get {
                return ((string)(this["APP_MSG_TTL"]));
            }
            set {
                this["APP_MSG_TTL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PT SHIMANO BATAM (PANBIL)")]
        public string APP_MSG_LOC {
            get {
                return ((string)(this["APP_MSG_LOC"]));
            }
            set {
                this["APP_MSG_LOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KEMEJA PUTIH, BAWAHAN HITAM")]
        public string APP_MSG_UNIFORM {
            get {
                return ((string)(this["APP_MSG_UNIFORM"]));
            }
            set {
                this["APP_MSG_UNIFORM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[TITLE]

Di beritahukan kepada, 

[NAME]
[PHONE]


Agar dapat hadir dan mengikuti tes tertulis yang,
dijadwalkan pada:

[DATE]
[TIME]
[LOCATION]
[UNIFORM]

Adapun beberapa berkas yang WAJIB di bawa : 

1.FTKP KTP & KK
2.FTKP NPWP (NPWP dapat dibuat secara online melalui https://ereg.pajak.go.id/daftar)
3.FTKP IJAZAH TERAKHIR
4.FTKP BUKU REK BCA (JIKA ADA)
5.FTKP KIS/BPJS KES & BPJS TK/JAMSOSTEK (JIKA ADA)
6.FTKP SIM C (JIKA ADA)
7.IJAZAH ASLI
8.PAS FOTO 3X4
9.PENA DAN LEM

SEMUA WAJIB mengikuti protokol kesehatan COVID-19 dengan cara menggunakan masker 
dan menerapkan Physical Distancing.

Undangan hanya berlaku 1 (satu) kali penggunaan dengan menunjukkan pesan panggilan ini secara fisik")]
        public string QR_MSG {
            get {
                return ((string)(this["QR_MSG"]));
            }
            set {
                this["QR_MSG"] = value;
            }
        }
    }
}
